---
language: go
sudo: false
notifications:
  email: joaosoft@gmail.com
jobs:
  include:
    - stage: test
      install:
        - go mod tidy
        - go mods vendor
      os: linux
      go: master
      script:
        - go build ./printer
        - go test ./printer
        - go test -coverprofile=coverage.txt -covermode=atomic ./printer
        - go test ./printer -bench=. -cpu=1,2,4,8

      after_success:
        - bash <(curl -s https://codecov.io/bash)